export const PATHS = {
  HOME: '/',
  VALUE_MAPPINGS: '/value-mappings',
  VALUE_MAPPING_DETAIL: '/value-mappings/:valueMapId',
  CREATE_PROJECT: '/projects/new',
  PROJECT_OVERVIEW: '/projects/:projectId',
  PROJECT_SETTINGS: '/projects/:projectId/settings',
  PROJECT_DEPLOYMENTS: '/projects/:projectId/deployments',
  PROJECT_VALUE_MAPPINGS: '/projects/:projectId/value-mappings',
  CREATE_MAPPING: '/projects/:projectId/mappings/new',
  MAPPING_EDITOR: '/projects/:projectId/mappings/:mappingId',
  MAPPING_DEPLOYMENT: '/projects/:projectId/mappings/:mappingId/deploy',
  MAPPING_TEST: '/projects/:projectId/mappings/:mappingId/test-lab',
  SCHEMA_LIBRARY: '/schemas',
  SCHEMA_DETAIL: '/schemas/:schemaId',
  TEMPLATE_LIBRARY: '/templates',
  SETTINGS: '/settings',
} as const;
