export {
  BUCKET_NAME,
  TABLE_NAMES,
  deploymentCurrentKey,
  deploymentHistorySortKey,
  deploymentSnapshotKey,
  runtimeSchemaPayloadKey,
  runtimeSnapshotKey,
  RUNTIME_BUCKET_NAME,
  RUNTIME_TABLE_NAMES,
  SCHEMAS_PREFIX,
  SNAPSHOTS_PREFIX,
  mappingConfigKey,
  mappingRevisionKey,
  valueTableRevisionRowsKey,
  mappingVersionKey,
  schemaContentKey,
  schemaDraftRevisionContentKey,
  schemaOriginalKey,
  schemaVersionContentKey,
  autoMapHistoryGsiPk,
  autoMapHistoryGsiSk,
  autoMapOpenGsiPk,
  autoMapOpenGsiSk,
  autoMapRunSk,
  autoMapSessionMetaSk,
  autoMapSessionPk,
  autoMapSuggestionSk,
  autoMapWorkUnitSk,
} from './config.js';
export { dynamoClient, s3Client } from './clients.js';
export {
  create as createMapping,
  delete as deleteMapping,
  duplicate as duplicateMapping,
  get as getMapping,
  listByProject as listMappingsByProject,
  mappings,
  update as updateMapping,
} from './mappings.js';
export {
  create as createDeployment,
  appendDeploymentHistory,
  createRollback as createRollbackDeployment,
  deployments,
  getActiveSnapshot,
  getCurrent as getCurrentDeployment,
  getCurrentAll as getCurrentDeployments,
  listHistory as listDeploymentHistory,
  listDeploymentHistory as listRuntimeDeploymentHistory,
  upsertActiveSnapshot,
} from './deployments.js';
export {
  create as createDeploymentOrchestration,
  deploymentOrchestrations,
  get as getDeploymentOrchestration,
  updateStatus as updateDeploymentOrchestrationStatus,
} from './deployment-orchestrations.js';
export {
  deploymentSummaries,
  get as getDeploymentSummary,
  initialize as initializeDeploymentSummary,
  listByAttention as listDeploymentSummariesByAttention,
  listByProject as listDeploymentSummariesByProject,
  listGlobal as listDeploymentSummariesGlobal,
  remove as removeDeploymentSummary,
  upsert as upsertDeploymentSummary,
} from './deployment-summaries.js';
export {
  create as createMappingVersion,
  get as getMappingVersion,
  getConfig as getMappingVersionConfig,
  list as listMappingVersions,
  mappingVersions,
  save as saveMappingVersion,
} from './mapping-versions.js';
export {
  get as getMappingRevision,
  getConfig as getMappingRevisionConfig,
  list as listMappingRevisions,
  mappingRevisions,
  save as saveMappingRevision,
} from './mapping-revisions.js';
export {
  create as createSchemaMetadata,
  delete as deleteSchemaMetadata,
  get as getSchemaMetadata,
  initializeDraft as initializeSchemaDraft,
  list as listSchemaMetadata,
  schemaMetadata,
  createVersion as createSchemaVersionRecord,
  updateStatus as updateSchemaMetadataStatus,
} from './schema-metadata.js';
export {
  backfillDeploymentSchemaBundles,
  backfillMappingSchemaPins,
  runSchemaReferenceBackfill,
  type SchemaReferenceBackfillReport,
} from './schema-reference-backfill.js';
export {
  get as getSchemaDraft,
  getCurrent as getCurrentSchemaDraft,
  list as listSchemaDrafts,
  save as saveSchemaDraft,
  schemaDrafts,
  setBasedOnVersion as setSchemaDraftBasedOnVersion,
} from './schema-drafts.js';
export {
  createFromDraft as createSchemaVersion,
  get as getSchemaVersion,
  getLatest as getLatestSchemaVersion,
  list as listSchemaVersions,
  schemaVersions,
  updateDerivedStatuses as updateSchemaVersionDerivedStatuses,
} from './schema-versions.js';
export {
  batchWrite as batchWriteSchemaNodes,
  batchWriteSchemaNodeIdentities,
  deleteBySchema as deleteSchemaNodesBySchema,
  getSchemaNodeIdentity,
  listSchemaNodeIdentities,
  listBySchema as listSchemaNodesBySchema,
  putSchemaNodeIdentity,
  queryContains as querySchemaNodesContains,
  schemaNodes,
} from './schema-nodes.js';
export {
  archive as archiveValueTable,
  backfillRevisionRowIds,
  createGlobal as createGlobalValueMap,
  createGlobalRevision as createGlobalValueMapRevision,
  createOverlayRevision as createValueMapOverlayRevision,
  createProjectLink as createValueMapProjectLink,
  create as createValueTable,
  createRevision as createValueTableRevision,
  get as getValueTable,
  getGlobal as getGlobalValueMap,
  getItem as getValueTableItem,
  getRevision as getValueTableRevision,
  getRevisionItem as getValueTableRevisionItem,
  listGlobal as listGlobalValueMaps,
  listByProject as listValueTablesByProject,
  listUsage as listValueTableUsage,
  migrateValueTablesToScopedModel,
  remove as deleteValueTable,
  resolveReference as resolveValueTableReference,
  valueTables,
} from './value-tables.js';
export {
  deleteMappingConfig,
  deleteValueTableRevisionRows,
  deleteSchemaContent,
  getSchemaDraftRevisionContent,
  getMappingConfig,
  getValueTableRevisionRows,
  getSchemaVersionContent,
  getOriginalSchemaContent,
  getSchemaContent,
  mappingConfig,
  putMappingConfig,
  putSchemaDraftRevisionContent,
  putOriginalSchemaContent,
  putProcessedSchemaContent,
  putSchemaVersionContent,
  putValueTableRevisionRows,
  schemaContent,
  valueTableRevisionsContent,
} from './s3/index.js';
export { create as createProject, delete as deleteProject, get as getProject, list as listProjects, projects, update as updateProject } from './projects.js';
export { logSyncActivity, SyncActivityError, type LogSyncActivityInput } from './sync-activity.js';

export type {
  CdmReSyncStatus,
  MappingConfig,
  MappingConfigOptions,
  MappingRuleProjectValueTableRef,
  MappingRevisionItem,
  SaveSchemaDraftInput,
  SaveSchemaDraftResult,
  SchemaDataFormat,
  SchemaDerivedStatus,
  SchemaDraftItem,
  DeploymentCurrentItem,
  DeploymentFreshness,
  DeploymentOperationStatus,
  DeploymentOperationType,
  DeploymentPromotionState,
  DeploymentAttentionState,
  DeploymentSummaryEnvironmentState,
  DeploymentSummaryItem,
  InitializeDeploymentSummaryInput,
  UpsertDeploymentSummaryInput,
  DeploymentHistoryItem,
  DeploymentEnvironment,
  DeploymentOrchestrationItem,
  DeploymentOrchestrationOperationType,
  DeploymentOrchestrationStatus,
  DeploymentItem,
  DeploymentSourceType,
  ActiveSnapshotItem,
  AppendDeploymentHistoryInput,
  DeploymentEnvironmentModel,
  RuntimeDeploymentEnvironment,
  PersistedDeploymentEnvironment,
  LegacyRuntimeDeploymentEnvironment,
  CreateDeploymentInput,
  CreateDeploymentOrchestrationInput,
  CreateRollbackDeploymentInput,
  CreateMappingInput,
  CreateProjectInput,
  CreateSchemaMetadataInput,
  CreateSchemaVersionInput,
  CreateSchemaVersionResult,
  CreateValueTableInput,
  CreateGlobalValueMapInput,
  CreateGlobalValueMapRevisionInput,
  CreateValueMapOverlayRevisionInput,
  CreateValueMapProjectLinkInput,
  CreateValueTableRevisionInput,
  GitHubSourceInfo,
  MappingItem,
  MappingMetadata,
  MappingStatus,
  MappingRule,
  MappingVersionItem,
  ProjectItem,
  ProjectDetail,
  ProjectMetadata,
  RuntimeDeploymentEventType,
  SchemaDiffEntry,
  SchemaDiffSummary,
  SchemaIngestStatus,
  SchemaIdentityNodePointer,
  SyncActivityItem,
  SchemaMetadata,
  SchemaMetadataItem,
  SchemaNodeIdentity,
  SchemaOwnership,
  SchemaNodeItem,
  SchemaOrigin,
  SchemaRef,
  SchemaRefType,
  SchemaScope,
  SchemaSourceInfo,
  SchemaSyncResult,
  SchemaSyncStatus,
  SchemaSourceKind,
  SchemaStatus,
  SchemaVersionItem,
  SchemaVersionStatus,
  ProjectValueTable,
  ProjectValueTableRevision,
  ProjectValueTableRevisionRow,
  ResolveValueTableReferenceInput,
  UpsertActiveSnapshotInput,
  UpdateDeploymentOrchestrationStatusInput,
  UpdateMappingInput,
  UpdateProjectInput,
  UploadSourceInfo,
  ValueTableDirectionSupport,
  ValueTableItem,
  ValueTablePrimitiveValue,
  ValueTableResolvedEntry,
  ValueTableRevisionItem,
  ValueTableSideDefinition,
  ValueTableStatus,
  ValueTableUsageEntry,
  ValueTableValueType,
  ValueMapDependencyState,
  ValueMapMatchMode,
  ValueMapOverlayOperation,
  ValueMapOverlayOperationType,
  ValueMapOverlayRevisionItem,
  ValueMapProjectLinkItem,
  ValueMapScope,
} from './types.js';
export {
  normalizeRuntimeDeploymentEnvironment,
  normalizeSchemaOwnership,
  normalizeSchemaSourceKind,
  normalizeSchemaStatus,
  schemaDataFormatFromSourceKind,
  toMappingMetadata,
  toProjectValueTable,
  toProjectDetail,
  toProjectMetadata,
  toSchemaMetadata,
} from './types.js';
export { computeConfigHash } from './hash.js';
export {
  assertExpectedSuggestionVersion,
  autoMapTransitions,
  buildHistoryIndexAttributes,
  buildInsertIfAbsentConditionExpression,
  buildOpenSessionIndexAttributes,
  buildRunNotSupersededCondition,
  buildSessionNotSupersededCondition,
  buildSuggestionExpectedVersionCondition,
  canTransitionRunStatus,
  canTransitionSessionStatus,
  canTransitionSuggestionReviewStatus,
  canTransitionWorkUnitStatus,
  createRequestFingerprint,
  nextSuggestionVersion,
  type AutoMapGenerationFingerprint,
  type AutoMapRequestFingerprintInput,
  type AutoMapRunItem,
  type AutoMapRunStatus,
  type AutoMapScopeMode,
  type AutoMapSessionItem,
  type AutoMapSessionStatus,
  type AutoMapSuggestionItem,
  type AutoMapWorkUnitItem,
  type AutoMapWorkUnitStatus,
  type SuggestionReviewStatus,
  type SuggestionSourceReference,
  type SuggestionValidationState,
} from './auto-map.js';
export {
  getAutoMapRun,
  getAutoMapSession,
  getAutoMapSuggestion,
  listAutoMapRuns,
  listAutoMapSuggestions,
  listAutoMapWorkUnits,
  listOpenSessionsByMapping,
  putAutoMapRun,
  putAutoMapRunIfAbsent,
  putAutoMapSession,
  putAutoMapSuggestion,
  putAutoMapSuggestions,
  putAutoMapWorkUnit,
  putAutoMapWorkUnitIfAbsent,
  supersedeSession,
  updateAutoMapRunProgress,
  updateAutoMapRunStatus,
  updateAutoMapSessionSummary,
  updateAutoMapWorkUnitStatus,
  updateSessionRunPointer,
} from './auto-map-store.js';
