export {
  BUCKET_NAME,
  TABLE_NAMES,
  deploymentCurrentKey,
  deploymentHistorySortKey,
  deploymentSnapshotKey,
  runtimeSchemaPayloadKey,
  runtimeSnapshotKey,
  RUNTIME_BUCKET_NAME,
  RUNTIME_TABLE_NAMES,
  SCHEMAS_PREFIX,
  SNAPSHOTS_PREFIX,
  mappingConfigKey,
  mappingRevisionKey,
  mappingVersionKey,
  schemaContentKey,
  schemaOriginalKey,
} from './config.js';
export { dynamoClient, s3Client } from './clients.js';
export {
  create as createMapping,
  delete as deleteMapping,
  duplicate as duplicateMapping,
  get as getMapping,
  listByProject as listMappingsByProject,
  mappings,
  update as updateMapping,
} from './mappings.js';
export {
  create as createDeployment,
  appendDeploymentHistory,
  createRollback as createRollbackDeployment,
  deployments,
  getActiveSnapshot,
  getCurrent as getCurrentDeployment,
  getCurrentAll as getCurrentDeployments,
  listHistory as listDeploymentHistory,
  listDeploymentHistory as listRuntimeDeploymentHistory,
  upsertActiveSnapshot,
} from './deployments.js';
export {
  create as createDeploymentOrchestration,
  deploymentOrchestrations,
  get as getDeploymentOrchestration,
  updateStatus as updateDeploymentOrchestrationStatus,
} from './deployment-orchestrations.js';
export {
  create as createMappingVersion,
  get as getMappingVersion,
  getConfig as getMappingVersionConfig,
  list as listMappingVersions,
  mappingVersions,
  save as saveMappingVersion,
} from './mapping-versions.js';
export {
  get as getMappingRevision,
  getConfig as getMappingRevisionConfig,
  list as listMappingRevisions,
  mappingRevisions,
  save as saveMappingRevision,
} from './mapping-revisions.js';
export {
  create as createSchemaMetadata,
  delete as deleteSchemaMetadata,
  get as getSchemaMetadata,
  list as listSchemaMetadata,
  schemaMetadata,
  updateStatus as updateSchemaMetadataStatus,
} from './schema-metadata.js';
export {
  batchWrite as batchWriteSchemaNodes,
  deleteBySchema as deleteSchemaNodesBySchema,
  listBySchema as listSchemaNodesBySchema,
  queryContains as querySchemaNodesContains,
  schemaNodes,
} from './schema-nodes.js';
export {
  deleteMappingConfig,
  deleteSchemaContent,
  getMappingConfig,
  getOriginalSchemaContent,
  getSchemaContent,
  mappingConfig,
  putMappingConfig,
  putOriginalSchemaContent,
  putProcessedSchemaContent,
  schemaContent,
} from './s3/index.js';
export { create as createProject, delete as deleteProject, get as getProject, list as listProjects, projects, update as updateProject } from './projects.js';
export { logSyncActivity, SyncActivityError, type LogSyncActivityInput } from './sync-activity.js';

export type {
  CdmReSyncStatus,
  MappingConfig,
  MappingConfigOptions,
  MappingRevisionItem,
  DeploymentCurrentItem,
  DeploymentHistoryItem,
  DeploymentEnvironment,
  DeploymentOrchestrationItem,
  DeploymentOrchestrationOperationType,
  DeploymentOrchestrationStatus,
  DeploymentItem,
  DeploymentSourceType,
  ActiveSnapshotItem,
  AppendDeploymentHistoryInput,
  DeploymentEnvironmentModel,
  RuntimeDeploymentEnvironment,
  PersistedDeploymentEnvironment,
  LegacyRuntimeDeploymentEnvironment,
  CreateDeploymentInput,
  CreateDeploymentOrchestrationInput,
  CreateRollbackDeploymentInput,
  CreateMappingInput,
  CreateProjectInput,
  CreateSchemaMetadataInput,
  GitHubSourceInfo,
  MappingItem,
  MappingMetadata,
  MappingStatus,
  MappingRule,
  MappingVersionItem,
  ProjectItem,
  ProjectDetail,
  ProjectMetadata,
  RuntimeDeploymentEventType,
  SchemaDiffEntry,
  SchemaDiffSummary,
  SchemaIngestStatus,
  SyncActivityItem,
  SchemaMetadata,
  SchemaMetadataItem,
  SchemaNodeItem,
  SchemaOrigin,
  SchemaRef,
  SchemaRefType,
  SchemaScope,
  SchemaSourceInfo,
  SchemaSyncResult,
  SchemaSyncStatus,
  UpsertActiveSnapshotInput,
  UpdateDeploymentOrchestrationStatusInput,
  UpdateMappingInput,
  UpdateProjectInput,
  UploadSourceInfo,
} from './types.js';
export {
  normalizeRuntimeDeploymentEnvironment,
  toMappingMetadata,
  toProjectDetail,
  toProjectMetadata,
  toSchemaMetadata,
} from './types.js';
export { computeConfigHash } from './hash.js';
